import { ExerciseType } from "@prisma/client";

// Dados curados da trilha (briefing docs/briefing.md, secoes 8 e 9).
// Extraidos do seed.ts pra dar pra testar o curriculo sem precisar de banco
// (ver src/exercises/curriculum.spec.ts): confere que nenhum exercicio de
// aprendizagem usa uma tecla ainda nao ensinada nos mundos anteriores.
//
// Tipado explicitamente (em vez de deixar o TS inferir): o projeto roda com
// `noImplicitAny: false`, entao sem essas interfaces o array cai pra `any`
// silenciosamente pro tsc -- e qualquer arquivo em src/ que importe daqui
// (como o teste acima) herda esse `any` e trava no eslint (regras
// no-unsafe-return/no-unsafe-argument), mesmo com tudo certo em tempo real.
interface WorldSeed {
  order: number;
  title: string;
  focus: string;
}

interface ExerciseSeed {
  worldOrder: number;
  order: number;
  title: string;
  type: ExerciseType;
  content: string;
  allowedKeys: string[];
  minAccuracy: number;
  targetWpm: number | null;
  minAttempts: number;
}

export const WORLDS_DATA: WorldSeed[] = [
    { order: 1, title: "Mundo 1: Base", focus: "Postura, F, J e linha guia" },
    { order: 2, title: "Mundo 2: Controle", focus: "Linha guia completa" },
    { order: 3, title: "Mundo 3: Alcance Superior", focus: "Linha superior" },
    { order: 4, title: "Mundo 4: Alcance Inferior", focus: "Linha inferior" },
    { order: 5, title: "Mundo 5: Coordenação", focus: "Shift, maiúsculas e alternância" },
    { order: 6, title: "Mundo 6: Português", focus: "Acentos, cedilha e pontuação" },
    { order: 7, title: "Mundo 7: Fluência", focus: "Palavras frequentes" },
    { order: 8, title: "Mundo 8: Ritmo", focus: "Frases e parágrafos" },
    { order: 9, title: "Mundo 9: Dados", focus: "Números e dados profissionais" },
    { order: 10, title: "Mundo 10: Precisão", focus: "Treinos de erro zero" },
    { order: 11, title: "Mundo 11: Velocidade", focus: "Sprints e consistência" },
    { order: 12, title: "Mundo 12: Elite", focus: "Testes avançados e conteúdo aberto" },
  ];

export const EXERCISES_DATA: ExerciseSeed[] = [
    // ---------------------------------------------------------------------
    // Mundo 1: Base -- linha guia completa (asdfghjklç), uma dupla de tecla
    // por vez (referencia TypingMaster/Mavis Beacon/Keybr.com: nunca saltar
    // direto pro conjunto inteiro de uma fileira). So depois das 5 duplas
    // introduzidas e praticadas isoladamente e que a consolidacao (combos,
    // bigramas, primeiras palavras) faz sentido.
    // ---------------------------------------------------------------------
    {
      worldOrder: 1,
      order: 1,
      title: "Fundação: F e J",
      type: ExerciseType.KEY_SEQUENCE,
      content: "fff jjj fjf jfj fff jjj fj jf ff jj fj jf",
      allowedKeys: ["f", "j"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 2,
      title: "D e K",
      type: ExerciseType.KEY_SEQUENCE,
      content: "ddd kkk dkd kdk ddd kkk dk kd dd kk dk kd",
      allowedKeys: ["d", "k"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 3,
      title: "S e L",
      type: ExerciseType.KEY_SEQUENCE,
      content: "sss lll sls lsl sss lll sl ls ss ll sl ls",
      allowedKeys: ["s", "l"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 4,
      title: "A e Ç — completa a linha guia",
      type: ExerciseType.KEY_SEQUENCE,
      content: "aaa ççç aça çaç aaa ççç aç ça aa çç aç ça",
      allowedKeys: ["a", "ç"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 5,
      title: "G e H — teclas de ponte",
      type: ExerciseType.KEY_SEQUENCE,
      content: "ggg hhh ghg hgh ggg hhh gh hg gg hh gh hg",
      allowedKeys: ["g", "h"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 6,
      title: "Linha guia completa: combinações",
      type: ExerciseType.KEY_SEQUENCE,
      content: "asdfgh jklç asdfgh jklç hgfdsa çlkjhg asdfgh jklç",
      allowedKeys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ç"],
      minAccuracy: 0.88,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 7,
      title: "Bigramas da linha guia",
      type: ExerciseType.BIGRAM,
      content: "as sd df fg gh hj jk kl lç ça aç gh fg sl dk fj kd",
      allowedKeys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ç"],
      minAccuracy: 0.88,
      targetWpm: 16,
      minAttempts: 3,
    },
    {
      worldOrder: 1,
      order: 8,
      title: "Primeiras palavras (linha guia)",
      // So palavras reais que usam SO letras da linha guia (a s d f g h j k l ç)
      // -- confere com o teste de conformidade em exercises-curriculum.spec.ts.
      type: ExerciseType.WORD_LIST,
      content: "sal sala salada salgada falsa falsas fada fadas asa asas alga algas gala galas saga alada",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 18,
      minAttempts: 2,
    },
    // ---------------------------------------------------------------------
    // Mundo 2: Controle -- consolida a MESMA linha guia (o foco do briefing
    // pra este mundo e "linha guia completa", nao letras novas -- essas
    // ficam pro Mundo 3). Fecha com um "checkpoint" que foge da regra de
    // propósito (ver comentario no ultimo exercicio).
    // ---------------------------------------------------------------------
    {
      worldOrder: 2,
      order: 1,
      title: "Trigramas da linha guia",
      type: ExerciseType.BIGRAM,
      content: "asd sdf dfg fgh ghj hjk jkl klç asd fgh jkl dfg",
      allowedKeys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ç"],
      minAccuracy: 0.88,
      targetWpm: 18,
      minAttempts: 3,
    },
    {
      worldOrder: 2,
      order: 2,
      title: "Alternância bilateral",
      // Habilidade "Coordenação" do briefing sec. 9 (alternancia fj fj jf jf):
      // mao esquerda e direita revezando, nao so repeticao na mesma mao.
      type: ExerciseType.KEY_SEQUENCE,
      content: "fj jf dk kd sl ls aç ça fj dk sl aç jf kd ls ça",
      allowedKeys: ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ç"],
      minAccuracy: 0.88,
      targetWpm: 20,
      minAttempts: 3,
    },
    {
      worldOrder: 2,
      order: 3,
      title: "Palavras curtas",
      // Corrigido: a lista antiga tinha "casa" (tem "c", fileira inferior,
      // so ensinada no Mundo 4) -- violava a propria regra do briefing sec.
      // 9 ("nao apresentar palavra com tecla ainda nao ensinada"). Substituida
      // por vocabulario 100% linha-guia.
      type: ExerciseType.WORD_LIST,
      content: "sal sala fada asa alga gala saga falsa",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 16,
      minAttempts: 2,
    },
    {
      worldOrder: 2,
      order: 4,
      title: "Mais palavras, mais rápido",
      // Mesmo vocabulario da linha guia (o idioma nao da pra variar muito
      // sem vogal alem do "a") -- repeticao espacada com meta de velocidade
      // maior, nao palavras novas.
      type: ExerciseType.WORD_LIST,
      content: "salada salgada fadas asas algas galas falsas alada",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 20,
      minAttempts: 2,
    },
    {
      worldOrder: 2,
      order: 5,
      title: "Checkpoint: primeira frase real",
      // EXCECAO DE PROPOSITO a regra do briefing sec. 9 ("...salvo quando a
      // atividade declarar explicitamente que e revisao ou teste"): usa
      // letras que so aparecem a partir do Mundo 3+, de proposito, como
      // previa motivadora ("olha ate onde voce vai chegar") -- nao e uma
      // atividade de dominio, por isso minAccuracy mais baixo e sem meta de
      // velocidade. Antes se chamava "Texto curto" e ficava dentro do
      // conjunto "normal" de exercicios, o que escondia essa excecao.
      type: ExerciseType.PHRASE,
      content: "a pratica leva a perfeicao aos poucos cada dia",
      allowedKeys: [],
      minAccuracy: 0.75,
      targetWpm: null,
      minAttempts: 1,
    },
    // ---------------------------------------------------------------------
    // Mundo 3: Alcance Superior -- 5 duplas novas, uma de cada vez (E/I sao
    // as mais frequentes fora do "a", ficam primeiro; Q/P sao rarissimas
    // isoladas em portugues, ficam por ultimo), so depois a consolidacao.
    // ---------------------------------------------------------------------
    {
      worldOrder: 3,
      order: 1,
      title: "E e I",
      type: ExerciseType.KEY_SEQUENCE,
      content: "eee iii eie iei eee iii ei ie ee ii ei ie",
      allowedKeys: ["e", "i"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 2,
      title: "R e U",
      type: ExerciseType.KEY_SEQUENCE,
      content: "rrr uuu rur uru rrr uuu ru ur rr uu ru ur",
      allowedKeys: ["r", "u"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 3,
      title: "T e Y",
      type: ExerciseType.KEY_SEQUENCE,
      content: "ttt yyy tyt yty ttt yyy ty yt tt yy ty yt",
      allowedKeys: ["t", "y"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 4,
      title: "W e O",
      type: ExerciseType.KEY_SEQUENCE,
      content: "www ooo wow owo www ooo wo ow ww oo wo ow",
      allowedKeys: ["w", "o"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 5,
      title: "Q e P",
      type: ExerciseType.KEY_SEQUENCE,
      content: "qqq ppp qpq pqp qqq ppp qp pq qq pp qp pq",
      allowedKeys: ["q", "p"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 6,
      title: "Linha superior: todas as combinações",
      type: ExerciseType.BIGRAM,
      content: "qw ei op wo qp asdfgh jklç ruty tyru opqw eiwo",
      allowedKeys: ["q", "w", "e", "i", "o", "p", "r", "u", "t", "y"],
      minAccuracy: 0.88,
      targetWpm: 18,
      minAttempts: 3,
    },
    {
      worldOrder: 3,
      order: 7,
      title: "Palavras com linha superior",
      type: ExerciseType.WORD_LIST,
      content: "trigo outro triste piquete requer poeira quieto",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 20,
      minAttempts: 2,
    },
    {
      worldOrder: 3,
      order: 8,
      title: "Frase curta",
      type: ExerciseType.PHRASE,
      // Trocado de "...do rei de roma" pra isto: a frase original tinha "m"
      // (em "roma"), que só é ensinado no Mundo 4 -- violava a própria regra
      // do briefing sec. 9 (achado pelo teste em exercises/curriculum.spec.ts).
      content: "o rato roeu o tapete rosa",
      allowedKeys: [],
      minAccuracy: 0.92,
      targetWpm: 22,
      minAttempts: 2,
    },
    // ---------------------------------------------------------------------
    // Mundo 4: Alcance Inferior -- mesma logica: as duas duplas combinadas
    // antigas (ZXCV, BNM+virgula) viram 4 passos separados.
    // ---------------------------------------------------------------------
    {
      worldOrder: 4,
      order: 1,
      title: "Z e X",
      type: ExerciseType.KEY_SEQUENCE,
      content: "zzz xxx zxz xzx zzz xxx zx xz zz xx zx xz",
      allowedKeys: ["z", "x"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 4,
      order: 2,
      title: "C e V",
      type: ExerciseType.KEY_SEQUENCE,
      content: "ccc vvv cvc vcv ccc vvv cv vc cc vv cv vc",
      allowedKeys: ["c", "v"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 4,
      order: 3,
      title: "B e N",
      type: ExerciseType.KEY_SEQUENCE,
      content: "bbb nnn bnb nbn bbb nnn bn nb bb nn bn nb",
      allowedKeys: ["b", "n"],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 4,
      order: 4,
      title: "M e vírgula",
      type: ExerciseType.KEY_SEQUENCE,
      content: "mmm ,,, m,m ,m, mmm ,,, m, ,m mm ,, m, ,m",
      allowedKeys: ["m", ","],
      minAccuracy: 0.85,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 4,
      order: 5,
      title: "Linha inferior: combinações",
      type: ExerciseType.BIGRAM,
      content: "zx cv bn m, za xc vb nm cz xv bm zn xb cm vn",
      allowedKeys: ["z", "x", "c", "v", "b", "n", "m", ","],
      minAccuracy: 0.87,
      targetWpm: 15,
      minAttempts: 3,
    },
    {
      worldOrder: 4,
      order: 6,
      title: "Palavras com linha inferior",
      type: ExerciseType.WORD_LIST,
      content: "vamos nunca começo menino banco campo cabe",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 18,
      minAttempts: 2,
    },
    {
      worldOrder: 4,
      order: 7,
      title: "Frase da linha inferior",
      type: ExerciseType.PHRASE,
      content: "nunca comece o exame sem calma",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 20,
      minAttempts: 2,
    },
    // Mundo 5: Coordenação (Shift, maiúsculas, alternância bilateral)
    {
      worldOrder: 5,
      order: 1,
      title: "Maiúsculas: Shift na linha guia",
      type: ExerciseType.KEY_SEQUENCE,
      content: "Aa Ss Dd Ff Jj Kk Ll Çç Aa Ss Dd Ff Jj Kk",
      allowedKeys: ["a", "s", "d", "f", "j", "k", "l", "ç"],
      minAccuracy: 0.82,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 5,
      order: 2,
      title: "Nomes próprios",
      type: ExerciseType.WORD_LIST,
      content: "Ana Rui Zeca Iara Duda Caio Nina Davi",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 15,
      minAttempts: 2,
    },
    {
      worldOrder: 5,
      order: 3,
      title: "Frases com maiúsculas",
      type: ExerciseType.PHRASE,
      content: "Maria foi ao Rio de Janeiro em Julho",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 18,
      minAttempts: 2,
    },
    {
      worldOrder: 5,
      order: 4,
      title: "Coordenação bilateral",
      type: ExerciseType.PHRASE,
      content: "A Bruna e o Pedro foram treinar juntos hoje",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 20,
      minAttempts: 2,
    },
    // Mundo 6: Português (acentos, cedilha e pontuação — ABNT2)
    {
      worldOrder: 6,
      order: 1,
      title: "Acentuação: agudo e circunflexo",
      type: ExerciseType.KEY_SEQUENCE,
      content: "á é í ó ú â ê ô á é í ó ú â ê ô",
      allowedKeys: [],
      minAccuracy: 0.8,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 6,
      order: 2,
      title: "Til e cedilha",
      type: ExerciseType.KEY_SEQUENCE,
      content: "ã õ ç ã õ ç ação ações mãe mão ímã",
      allowedKeys: [],
      minAccuracy: 0.8,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 6,
      order: 3,
      title: "Palavras acentuadas",
      type: ExerciseType.WORD_LIST,
      content: "café área saúde história público última função",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 16,
      minAttempts: 2,
    },
    {
      worldOrder: 6,
      order: 4,
      title: "Pontuação básica",
      type: ExerciseType.PHRASE,
      content: "Você já foi à padaria, não é? Sim, claro!",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 16,
      minAttempts: 2,
    },
    {
      worldOrder: 6,
      order: 5,
      title: "Frase completa em português",
      type: ExerciseType.PHRASE,
      content: "A comunicação clara é essencial no dia a dia",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 18,
      minAttempts: 2,
    },
    // Mundo 7: Fluência (palavras frequentes)
    {
      worldOrder: 7,
      order: 1,
      title: "Palavras mais comuns 1",
      type: ExerciseType.WORD_LIST,
      content: "que não uma para com mais como foi pelo",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 22,
      minAttempts: 2,
    },
    {
      worldOrder: 7,
      order: 2,
      title: "Palavras mais comuns 2",
      type: ExerciseType.WORD_LIST,
      content: "isso porque quando tempo sobre ainda outros",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 24,
      minAttempts: 2,
    },
    {
      worldOrder: 7,
      order: 3,
      title: "Vocabulário do dia a dia",
      type: ExerciseType.WORD_LIST,
      content: "trabalho família amigos escola cidade governo",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 26,
      minAttempts: 2,
    },
    {
      worldOrder: 7,
      order: 4,
      title: "Frase fluida",
      type: ExerciseType.PHRASE,
      content: "o tempo passa rápido quando estamos ocupados",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 28,
      minAttempts: 2,
    },
    // Mundo 8: Ritmo (frases e parágrafos)
    {
      worldOrder: 8,
      order: 1,
      title: "Frase longa",
      type: ExerciseType.PHRASE,
      content: "a persistência é o caminho mais curto para o sucesso verdadeiro",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 26,
      minAttempts: 2,
    },
    {
      worldOrder: 8,
      order: 2,
      title: "Duas frases",
      type: ExerciseType.PHRASE,
      content: "o sol nasceu cedo hoje. o dia promete ser produtivo e tranquilo.",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 28,
      minAttempts: 2,
    },
    {
      worldOrder: 8,
      order: 3,
      title: "Parágrafo curto",
      type: ExerciseType.PHRASE,
      content: "a tecnologia mudou a forma como aprendemos. hoje, qualquer pessoa pode estudar de casa, no seu próprio ritmo, sem sair do lugar.",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 30,
      minAttempts: 2,
    },
    {
      worldOrder: 8,
      order: 4,
      title: "Parágrafo com pontuação",
      type: ExerciseType.PHRASE,
      content: "você já parou para pensar no quanto pratica todos os dias? cada linha digitada é um passo a mais rumo à fluência.",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 30,
      minAttempts: 2,
    },
    // Mundo 9: Dados (números e dados profissionais fictícios)
    {
      worldOrder: 9,
      order: 1,
      title: "Sequência numérica",
      type: ExerciseType.NUMBERS,
      content: "123 456 789 000 111 222 333 444 555 2026",
      allowedKeys: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
      minAccuracy: 0.85,
      targetWpm: 18,
      minAttempts: 3,
    },
    {
      worldOrder: 9,
      order: 2,
      title: "Datas e valores",
      type: ExerciseType.NUMBERS,
      content: "07/08/2026 15/01/2027 R$ 1.234,56 R$ 89,90",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 16,
      minAttempts: 3,
    },
    {
      worldOrder: 9,
      order: 3,
      title: "Cadastro fictício",
      type: ExerciseType.PROFESSIONAL_DATA,
      content: "Nome: João Silva CPF: 123.456.789-00 Tel: (11) 91234-5678",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 18,
      minAttempts: 2,
    },
    {
      worldOrder: 9,
      order: 4,
      title: "Dados de contato fictícios",
      type: ExerciseType.PROFESSIONAL_DATA,
      content: "email: contato@empresa.com.br CEP: 01310-100",
      allowedKeys: [],
      minAccuracy: 0.85,
      targetWpm: 18,
      minAttempts: 2,
    },
    // Mundo 10: Precisão (treinos de erro zero)
    {
      worldOrder: 10,
      order: 1,
      title: "Precisão total: linha guia",
      type: ExerciseType.KEY_SEQUENCE,
      content: "asdf jklç asdf jklç asdf jklç asdf jklç",
      allowedKeys: ["a", "s", "d", "f", "j", "k", "l", "ç"],
      minAccuracy: 0.97,
      targetWpm: null,
      minAttempts: 3,
    },
    {
      worldOrder: 10,
      order: 2,
      title: "Precisão total: palavras",
      type: ExerciseType.WORD_LIST,
      content: "casa mesa fase dado gado saga jada alada",
      allowedKeys: [],
      minAccuracy: 0.97,
      targetWpm: 20,
      minAttempts: 3,
    },
    {
      worldOrder: 10,
      order: 3,
      title: "Zero erros: frase curta",
      type: ExerciseType.PHRASE,
      content: "a prática exige atenção total e sem pressa",
      allowedKeys: [],
      minAccuracy: 0.98,
      targetWpm: 20,
      minAttempts: 3,
    },
    {
      worldOrder: 10,
      order: 4,
      title: "Zero erros: frase com pontuação",
      type: ExerciseType.PHRASE,
      content: "você consegue, só precisa de foco e calma!",
      allowedKeys: [],
      minAccuracy: 0.98,
      targetWpm: 22,
      minAttempts: 3,
    },
    // Mundo 11: Velocidade (sprints e consistência)
    {
      worldOrder: 11,
      order: 1,
      title: "Sprint de palavras curtas",
      type: ExerciseType.WORD_LIST,
      content: "sol mar paz luz voz flor casa gato livro porta mesa fogo água vento pedra nuvem praia tempo papel chave",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 35,
      minAttempts: 3,
    },
    {
      worldOrder: 11,
      order: 2,
      title: "Sprint de frase",
      type: ExerciseType.PHRASE,
      content: "a velocidade vem naturalmente quando a técnica está bem treinada",
      allowedKeys: [],
      minAccuracy: 0.88,
      targetWpm: 38,
      minAttempts: 3,
    },
    {
      worldOrder: 11,
      order: 3,
      title: "Texto de resistência",
      type: ExerciseType.PHRASE,
      content: "digitar rápido não significa digitar com pressa. a consistência é o que separa um bom digitador de um digitador excelente.",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 40,
      minAttempts: 3,
    },
    // Mundo 12: Elite (testes avançados e conteúdo aberto)
    {
      worldOrder: 12,
      order: 1,
      title: "Texto técnico",
      type: ExerciseType.PHRASE,
      content: "o sistema processa até 10.000 registros por segundo, com precisão de 99,9% e latência menor que 50ms.",
      allowedKeys: [],
      minAccuracy: 0.92,
      targetWpm: 45,
      minAttempts: 3,
    },
    {
      worldOrder: 12,
      order: 2,
      title: "Símbolos e parênteses",
      type: ExerciseType.PHRASE,
      content: "a função soma(a, b) retorna [a+b]; use {chaves} quando necessário.",
      allowedKeys: [],
      minAccuracy: 0.9,
      targetWpm: 40,
      minAttempts: 3,
    },
    {
      worldOrder: 12,
      order: 3,
      title: "Texto longo de alta performance",
      type: ExerciseType.PHRASE,
      content: "a excelência em digitação combina velocidade, precisão e consistência ao longo do tempo, sem depender de sorte em uma única tentativa.",
      allowedKeys: [],
      minAccuracy: 0.93,
      targetWpm: 50,
      minAttempts: 3,
    },
  ];
